# Site settings
title: "404：存在しないはずの記憶"
description: 誰にも語られることのなかった「本物の」怪異
url: ""
baseurl: ""

# Build settings
markdown: kramdown

# Collections
collections:
  posts:
    output: true
    permalink: /posts/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Plugins
plugins:
  - jekyll-minifier

# Sass settings
sass:
  style: compressed
